[book]
language = "en"
multilingual = false
src = "."
title = "goct Documentation"

[output.html]
git-repository-url = "https://github.com/kmdkuk/goct"
edit-url-template = "https://github.com/kmdkuk/goct/edit/main/docs/{path}"
site-url = "/goct/"
